package com.example.inu.global.s3;


public enum ErrorCode {
    EMPTY_FILE_EXCEPTION,
    IO_EXCEPTION_ON_IMAGE_UPLOAD,
    IO_EXCEPTION_ON_FILE_UPLOAD,
    NO_FILE_EXTENSION,
    INVALID_FILE_EXTENSION,
    INVALID_DOCUMENT_EXTENSION,
    PUT_OBJECT_EXCEPTION,
    IO_EXCEPTION_ON_IMAGE_DELETE,
    IO_EXCEPTION_ON_FILE_DELETE
}